config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'articles#index'

  get '/bubbly' => 'articles#index'
  get '/new_article' => 'articles#new'
  post '/new_article' => 'articles#create'
  get '/edit/:id/article' => 'articles#edit', as: 'edit_article'
  put '/edit/:id/article' => 'articles#update', as: 'update_article'
  delete '/:id/article' => 'articles#destroy', as: 'delete_article'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new; end

  def create
    @article = Article.new(article_data)
    # @article.title = params[:title]
    # @article.lyrics = params[:lyrics]
    if @article.save
      redirect_to bubbly_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_data)
      redirect_to bubbly_path
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      redirect_to bubbly_path
    else
      render :index
    end
  end

  private

  def article_data
    params.require(:article).permit(:title, :lyrics)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/articles/_new_form.html.erb
<h1>This is the form</h1>

<%= form_with scope: :article, locale: true do |f| %>

<div>
  <th><%= f.label :Title %></th>
  <th><%= f.text_field :title %></th>
</div>
<div>
  <th><%= f.label :Lyrics%></th>
  <th><%= f.text_field :lyrics %></th>
</div>

<div>
  <%= f.submit :"Submit" %>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>EDIT PAGE </h1>

<%= form_with scope: :article, method: :put, locale: true do |f| %>

<div>
  <th><%= f.label :Title %></th>
  <th><%= f.text_field :title %></th>
</div>
<div>
  <th><%= f.label :Lyrics%></th>
  <th><%= f.text_field :lyrics %></th>
</div>

<div>
  <%= f.submit :"Update" %>
</div>
<% end %>

app/views/articles/index.html.erb
<h1> ARTICLES </h1>

<%= link_to "Create", new_article_path %>

<% @articles.each do |arti| %>
<table>
<tr> 
  <td><%=arti.id%></td>
  <td> <%=arti.title%></td>
  <td> <%=arti.lyrics%></td>
  <td><%= link_to "EDIT", edit_article_path(arti.id) %></td>
  <td><%= link_to "Delete", delete_article_path(arti.id), method: :delete, data: { confirm: "Are you sure?" }  %></td>
</tr>
</table>
<% end %>

app/views/articles/new.html.erb
<h1> NEW NEW NEW </h1>
<%= render "new_form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MbmTestProj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>